version: '3.8'

services:
  api:
    container_name: perfect-api
    image: perfect-api
    restart: unless-stopped
    env_file:
      - .dev.vars
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - perfect-api:latest
    healthcheck:
      test: curl --silent -f http://localhost:5000 > /dev/null && exit 1 || exit 0
      interval: 5s
      timeout: 5s
      retries: 0
      start_period: 1s
    ports:
      - ${PORT-5000}:${PORT-5000}
