version: '3.8'

services:
  api:
    image: perfect-api
    restart: unless-stopped
    env_file:
      - .dev.vars
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: curl --silent -f http://localhost:3000/healthcheck/v1 > /dev/null && exit 1 || exit 0
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s
    ports:
      - ${PORT-3000}:${PORT-3000}
