name: API Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest

      - name: Install
        run: bun install

      - name: Prisma Generate
        run: bun run prisma:generate

      - name: Build
        run: bun build --minify --target=bun ./src/server.ts --outfile server.js

      - name: Upload bun api release
        uses: actions/upload-artifact@v3
        with:
          name: bun-api-release
          path: server.js
